---
- name: playbook Ubuntu Install
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    # ============================================
    # Faz algums pré-configurações iniciais
    # ============================================
    - name: "Install pré configs"
      include_tasks: "src/pre-config.yaml"

  tasks:
    # ============================================
    # instala ferramentas, dependencies e programas utils
    # ============================================
    - name: "Install packages and dependencies"
      become: true
      become_method: sudo
      apt:
        name: "{{ packages }}"

    # ============================================
    # Instalando o Visual Studio Code
    # ============================================
    - name: "Install VS Code"
      include_tasks: "src/packages/vscode/vscode-installer.yaml"

    # ============================================
    # Instalando o Spotify
    # ============================================
    - name: "Install Spotify"
      include_tasks: "src/packages/spotify/spotify-installer.yaml"

    # ===========================================
    # Instalando o Dropbox
    # ===========================================
    - name: "Install Dropbox"
      include_tasks: "src/packages/dropbox/dropbox-installer.yaml"

    # ===========================================
    # Instalando o Google Chrome
    # ===========================================
    - name: "Install Google Chrome"
      include_tasks: "src/packages/google-chrome/google-chrome-installer.yaml"

    # ===========================================
    # Instalando o InSync
    # ===========================================
    - name: "Install Insync"
      include_tasks: "src/packages/insync/insync-installer.yaml"

    # ===========================================
    # Clean nas depêndencias do apt-get
    # ===========================================
    - name: "Clean Environment"
      include_tasks: "src/clean-environment.yaml"

    # ===========================================
    # Instalando os meus dotfiles
    # ===========================================
    - name: "Download my dotfiles"
      include_tasks: "download-dotfiles.yaml"