---
- name: playbook Ubuntu Install
  hosts: localhost
  connection: local
  gather_facts: false

  pre_tasks:
    - name: UTILS - get username
      shell: whoami
      register: username

  tasks:
    # ============================================
    # Criando o diretório $HOME/bin
    # ============================================
    - name: UBUNTU - Create $HOME/bin Directory
      file:
        path: "$HOME/bin"
        state: directory
        mode: 0700

    # ============================================
    # Removendo os diretório do #HOME que eu não uso
    # ============================================
    - name: UBUNTU - Remove useless folders
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "~/Templates"
        - "~/examples.desktop"

    # ============================================
    # Criando o diretório de autostart
    # ============================================
    - name: UBUNTU - create autostart folder
      file:
       path: "$HOME/.config/autostart"
       state: directory

    # ============================================
    # instala ferramentas, dependencies e programas utils
    # ============================================
    - name: UBUNTU - Install packages and dependencies
      become: true
      become_method: sudo
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - git
        - git-extras
        - net-tools
        - meld
        - jq
        - vim
        - nano
        - gdebi-core
        - gnome-tweak-tool
        # - nautilus-compare
        - gnome-sushi
        - imagemagick
        - ubuntu-restricted-extras
        - neofetch
        - terminator
        - apt-transport-https
        - zip
        - gzip
        - unzip
        - bzip2
        - tar
        - chrome-gnome-shell
        - xclip
        - ffmpeg
        - baobab
        - dconf-editor

    # ============================================
    # Instalando o Visual Studio Code
    # ============================================
    - import_tasks: vs_code_install.yaml

    # ============================================
    # Instalando o Spotify
    # ============================================
    - import_tasks: spotify/spotify_install.yaml

    # ===========================================
    # Instalando o Dropbox
    # ===========================================
    - include_tasks: dropbox/dropbox_install.yaml
      vars:
        user: "{{ username.stdout }}"

    # ===========================================
    # Instalando o Google Chrome
    # ===========================================
    - include_tasks: google_chrome_install.yaml

    # ===========================================
    # Clean Dependencies
    # ===========================================
    # pra consertar possíveis dependencias e pacotes quebrados
    - name: CLEAN - Fix broken packages
      become: true
      become_method: sudo
      shell: apt -f -y install

    # deletar os pacotes .deb em '/var/cache/apt/archives/'
    - name: CLEAN - Remove useless packages from the cache
      become: true
      become_method: sudo
      apt:
        autoclean: yes

    # remover pacotes não mais utilizados
    - name: CLEAN - Remove dependencies that are no longer required
      become: true
      become_method: sudo
      apt:
        autoremove: yes

    # ===========================================
    # Instalando os meus dotfiles
    # ===========================================
    - include_tasks: dotfiles.yaml
      vars:
        user: "{{ username.stdout }}"
        git_name: "{{ user_on_git }}"
        git_email: "{{ email_on_git }}"