---
- name: Ubuntu Install - Telegram
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    telegram_folder: $HOME/bin/Telegram

  tasks:
    - name: TELEGRAM - create directory
      file:
        path: "{{ telegram_folder }}"
        state: directory

    - name: "TELEGRAM - Download"
      get_url:
        url: "{{ item }}"
        dest: "{{ telegram_folder }}"
      loop:
        - https://telegram.org/dl/desktop/linux
        - https://telegram.org/img/t_logo.png

    - name: TELEGRAM - Find XZ file
      find:
        paths: "{{ telegram_folder }}"
        patterns: "*.xz"
      register: result_xz

    - name: TELEGRAM - Extract file
      shell: tar -xvf {{ result_xz.files[0].path }} -C "{{ telegram_folder }}"
      args:
        warn: false

    - name: TELEGRAM - Find PNG file
      find:
        paths: "{{ telegram_folder }}"
        patterns: "*.png"
      register: result_png

    - name: TELEGRAM - Convert logo image size
      shell: convert -resize 128x128 {{ result_png.files[0].path }} {{ telegram_folder }}/telegram_logo.png

    - name: TELEGRAM - remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ result_xz.files[0].path }}"
        - "{{ result_png.files[0].path }}"

    - name: TELEGRAM - get username
      shell: whoami
      register: username

    - name: TELEGRAM - set user
      set_fact:
        user: "{{ username.stdout_lines }}"

    - name: TELEGRAM - generate desktop file
      template:
        src: "telegram.desktop.j2"
        dest: "$HOME/.local/share/applications/telegram.desktop"