---
- name: Ubuntu Install - VirtualBox
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: "VIRTUALBOX | Download .deb file"
      get_url:
        url: "https://download.virtualbox.org/virtualbox/6.1.14/virtualbox-6.1_6.1.14-140239~Ubuntu~eoan_amd64.deb"
        dest: "."

    - name: "VIRTUALBOX | Installing"
      become: true
      become_method: sudo
      shell: gdebi --non-interactive virtualbox-6.1_6.1.14-140239~Ubuntu~eoan_amd64.deb

    - name: "VIRTUALBOX | Removing installer"
      file:
        path: "virtualbox-6.1_6.1.14-140239~Ubuntu~eoan_amd64.deb"
        state: absent