---
# ===========================================
# Clean Dependencies
# ===========================================
# pra consertar possíveis dependencias e pacotes quebrados
- name: "CLEAN | Fix broken packages"
  become: true
  become_method: sudo
  shell: apt -f -y install

# deletar os pacotes .deb em '/var/cache/apt/archives/'
- name: "CLEAN | Remove useless packages from the cache"
  become: true
  become_method: sudo
  apt:
    autoclean: yes

# remover pacotes não mais utilizados
- name: "CLEAN | Remove dependencies that are no longer required"
  become: true
  become_method: sudo
  apt:
    autoremove: yes